### ISSUE TITLE
Typo in the repo's about section

### ISSUE THREAD

**Issue by attilapiros** [holdenk/spark-flowchart#25]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/2017933/177667862-581a2b42-746a-4b3a-a344-44a7ed1aacd9.png">

"Flowchart for debugging Spark aplications" => "Flowchart for debugging Spark a**pp**lications"

**Comment by attilapiros** [comment]
cc @atbida

**Comment by atbida** [comment]
Thank you @attilapiros but I don't have permission. @holdenk can you check?

**Comment by holdenk** [comment]
oh good point, yeah :)

**Comment by holdenk** [comment]
Fixed :) thanks!
